import os
import json
import argparse

class GenesisSeed:
    """
    THE WORLD SEED (Type: Creation)
    ------------------------------
    Standardized Project Instantiation capable of spawning new 'Worlds'.
    """
    
    def __init__(self):
        self.default_physics = {
            "gravity": "standard", # Linter strictness
            "magic": ["python", "node"], # Allowed Runtimes
            "permadeath": False, # implementation of strict git history
            "time_dilation": 1.0 # Clock speed relative to Anchor
        }
        
        self.default_bestiary = [
            {"name": "Linter Daemon", "type": "Guardian", "aggressive": True},
            {"name": "Test Runner", "type": "Golem", "aggressive": False}
        ]

    def plant_seed(self, target_dir):
        """
        [GENESIS]: Plants the Seed Package in the target directory.
        Creates:
          - .genesis/ (The Core)
          - .genesis/physics.json (The Laws)
          - .genesis/bestiary.json (The Agents)
          - LORE.md (The History)
        """
        genesis_dir = os.path.join(target_dir, ".genesis")
        
        if os.path.exists(genesis_dir):
            print(f"[Seed] A World already exists here: {target_dir}")
            return False

        print(f"[Seed] Planting Genesis in: {target_dir}...")
        os.makedirs(genesis_dir)

        # 1. Physics (The Laws)
        with open(os.path.join(genesis_dir, "physics.json"), "w") as f:
            json.dump(self.default_physics, f, indent=2)
            
        # 2. Bestiary (The Agents)
        with open(os.path.join(genesis_dir, "bestiary.json"), "w") as f:
            json.dump(self.default_bestiary, f, indent=2)

        # 3. Lore (The History)
        lore_content = f"""# The World of {os.path.basename(target_dir)}
        
> "Generated by the Genesis Seed on {os.getcwd()}"

## The Laws (Physics)
This world is governed by the following strictures:
- **Gravity:** {self.default_physics['gravity']}
- **Magic:** {", ".join(self.default_physics['magic'])}

## The Map
- **Floor 1:** Initialization
- **Floor 100:** Singularity
"""
        with open(os.path.join(target_dir, "LORE.md"), "w") as f:
            f.write(lore_content)

        print("[Seed] Germination Complete. The World is born.")
        return True

# --- CLI INTERFACE ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Genesis Seed Planter")
    parser.add_argument("--path", help="Target directory for the new World", default=os.getcwd())
    args = parser.parse_args()
    
    seed = GenesisSeed()
    seed.plant_seed(args.path)
