[build]
rustflags = ["-C", "target-cpu=native", "-C", "opt-level=3"]

[profile.release]
lto            = "fat"
codegen-units  = 1
panic          = "abort"
opt-level      = 3
strip          = "symbols"
